### ISSUE TITLE
Fresh install doesn't work due to the Lambda runtime parameter of nodejs14.x is no longer supported

### ISSUE THREAD

**Issue by chrismld** [aws-solutions-library-samples/guidance-for-ec2-spot-placement-score-tracker#3]
I had to deploy this solution using a fresh new account and I had the following problems while deploying:

```
12:16:26 PM | CREATE_FAILED        | AWS::Lambda::Function      | LogRetentionaae0aa...b201efdd8aFD4BFC8A
Resource handler returned message: "The runtime parameter of nodejs14.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs20.x) while creating or upda
ting functions. (Service: Lambda, Status Code: 400, Request ID: a51af9b2-12a3-442a-ba18-45569c6552c0)" (RequestToken: 62ace089-cd52-56f4-db27-8ad8601ef421, HandlerErrorCode: InvalidRequest)


 ❌  spot-placement-score-dashboard failed: Error: The stack named spot-placement-score-dashboard failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "The runtime parameter of nodejs14.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs20.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: a51af9b2-12a3-442a-ba18-45569c6552c0)" (RequestToken: 62ace089-cd52-56f4-db27-8ad8601ef421, HandlerErrorCode: InvalidRequest)
    at FullCloudFormationDeployment.monitorDeployment (/home/ec2-user/.nvm/versions/node/v20.11.1/lib/node_modules/aws-cdk/lib/index.js:427:10615)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/home/ec2-user/.nvm/versions/node/v20.11.1/lib/node_modules/aws-cdk/lib/index.js:430:196919)
    at async /home/ec2-user/.nvm/versions/node/v20.11.1/lib/node_modules/aws-cdk/lib/index.js:430:178888

 ❌ Deployment failed: Error: The stack named spot-placement-score-dashboard failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "The runtime parameter of nodejs14.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs20.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: a51af9b2-12a3-442a-ba18-45569c6552c0)" (RequestToken: 62ace089-cd52-56f4-db27-8ad8601ef421, HandlerErrorCode: InvalidRequest)
    at FullCloudFormationDeployment.monitorDeployment (/home/ec2-user/.nvm/versions/node/v20.11.1/lib/node_modules/aws-cdk/lib/index.js:427:10615)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/home/ec2-user/.nvm/versions/node/v20.11.1/lib/node_modules/aws-cdk/lib/index.js:430:196919)
    at async /home/ec2-user/.nvm/versions/node/v20.11.1/lib/node_modules/aws-cdk/lib/index.js:430:178888

The stack named spot-placement-score-dashboard failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "The runtime parameter of nodejs14.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs20.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: a51af9b2-12a3-442a-ba18-45569c6552c0)" (RequestToken: 62ace089-cd52-56f4-db27-8ad8601ef421, HandlerErrorCode: InvalidRequest)
```

It turns out that the `requirements.txt` is referencing to an old CDK library, the solution is to simply update this reference to the latest version `2.133.0`. I'm working on creating a new PR to fix this problem.

**Comment by ruecarlo** [comment]
#5 , #4  both fix the documentation closes did update the issue and updated the instruction and documentation.
